version: '3.9'

services:
  elasticsearch:
    image: elasticsearch:8.5.1
    networks:
      - elasticsearch_network
    ports:
      - 9200:9200
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - ./env/elasticsearch.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 500M

networks:
  elasticsearch_network: 
    name: elasticsearch_network
    driver: overlay
    driver_opts:
      encrypted: true